services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        environment:
            APP_URL: ${APP_URL}
        ports:
            - '${NGINX_FORWARD_PORT:-80}:80'
            - '${NGINX_FORWARD_PORT_SECURE:-443}:443'
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./storage/logs:/var/log/nginx
            - ./public:/var/www/html/public:ro
        networks:
            - payment
        depends_on:
            - app
    app:
        image: payment-es-app
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
            target: dev
            args:
                PHP_VERSION: 8.4
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - .:/var/www/html:delegated
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - payment
        healthcheck:
            test: pgrep php-fpm
            retries: 20
            timeout: 5s
        depends_on:
            mariadb:
                condition: service_healthy
    mariadb:
        image: mariadb:latest
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - payment
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
    horizon:
        image: payment-es-app
        command: php artisan horizon
        volumes:
            - .:/var/www/html:delegated
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - payment
        stop_signal: SIGTERM
        depends_on:
            app:
                condition: service_healthy
            mariadb:
                condition: service_healthy
    scheduler:
        extends:
            service: horizon
        command: php artisan schedule:work
    redis:
        image: redis:alpine
        networks:
            - payment
networks:
    payment:
        driver: bridge
volumes:
    db-data:
        driver: local
