#!/usr/bin/env sh

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

chown -R $(id -u):$(id -g) ./storage
chmod -R ugo+rw storage

composer i --no-interaction
php artisan migrate

if [ $# -gt 0 ]; then
    exec "$@"
else
    exec php-fpm
fi
